//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Group
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int loans_ID { get; set; }
        public string emp_ID { get; set; }
        public Nullable<int> how_many { get; set; }
        public string descs { get; set; }
    }
}
